[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["greeting_service3"]
  icon = "docs/icon.png"
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "greeting_service3"
  org = "yashodperera"
  version = "1.1.0"

